# Generated by Django 5.2.10 on 2026-01-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jewelry_images/'),
        ),
        migrations.AlterField(
            model_name='jewelryitem',
            name='purity',
            field=models.CharField(choices=[('14K', '14K'), ('18K', '18K'), ('22K', '22K'), ('925', '925'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
