# Generated by Django 5.2.10 on 2026-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_purity_choices_and_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryitem',
            name='purity',
            field=models.CharField(choices=[('14K', '14K'), ('18K', '18K'), ('22K', '22K'), ('925K', '925K'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
