# Generated by Django 5.2.10 on 2026-02-05 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_supplier_vat_number'),
        ('inventory', '0003_alter_jewelryitem_purity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jewelry_items', to='crm.supplier'),
        ),
    ]
