# Generated by Django 5.2.10 on 2026-02-04 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_supplier_vat_number'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='crm.customer'),
        ),
    ]
