# Generated by Django 5.2.10 on 2026-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT Registration Number'),
        ),
    ]
